HomeWork 7
VAgranovich/java01 pull request #7
Opened 2022-05-15 18:49 UTC by VAgranovich

2022-05-16 15:22 UTC, efserg requested changes

2022-05-16 15:22 UTC, efserg commented on src/main/java/ru/gb/vagranovich/homework7/Plate.java
> +            lackOfFood = true;
Не пойдет. 
Что будет, если в тарелке 2 единицы еды, сначала придет кот с аппетитом 5, потом с аппетитом 1? Они оба останутся голодными?

2022-05-16 15:22 UTC, efserg commented on src/main/java/ru/gb/vagranovich/homework7/Plate.java
> +    public void info() {
Есть метод toString, его использование предпочтительнее

2022-05-22 18:47 UTC, VAgranovich commented on src/main/java/ru/gb/vagranovich/homework7/Plate.java
> +            lackOfFood = true;
Добавил строчку (выделена жирным), которая позволяет исключить такую ситуацию
------------------------------       
if (food >= n) {
            food -= n;
            **lackOfFood = false;**
        } else {
            lackOfFood = true;

2022-05-22 18:55 UTC, merged